# Generated by Django 4.1.7 on 2023-06-27 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=50)),
                ('photo_book', models.ImageField(blank=True, null=True, upload_to='photos/books/%y%m%d')),
                ('photo_author', models.ImageField(blank=True, null=True, upload_to='photos/author/%y%m%d')),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retail_period', models.IntegerField(blank=True, null=True)),
                ('total_retail', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('active', models.BooleanField(choices=[(True, 'active'), (False, 'Not active')], default=True)),
                ('status', models.CharField(choices=[('available', 'available'), ('retailed', 'retailed'), ('sold', 'sold')], max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='LMS.category')),
            ],
        ),
    ]
