# Generated by Django 4.1.7 on 2023-07-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_book_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='photo_author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='retail_period',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_retail',
        ),
        migrations.AlterField(
            model_name='book',
            name='active',
            field=models.BooleanField(choices=[(True, 'active'), (False, 'Not active'), (False, 'Out of Sotck')], default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('retailed', 'retailed'), ('sold', 'sold'), ('outOfStock', 'Out Of Stock')], max_length=50),
        ),
    ]
