# Generated by Django 4.1.7 on 2023-07-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0004_book_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'managed': True, 'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='book',
            table='',
        ),
    ]
